___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy 

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy. To get started we need to install it!

## Installation Instructions

### NumPy is already included in your environment! You are good to go if you are using the course environment!

_____
##### For those not using the provided environment:

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](https://www.scipy.org/install.html)**

_____

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_list

[1, 2, 3]

In [5]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_mat = np.array(my_matrix)
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# all the atttributes of a numpy matrix object:
dir(my_mat)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [9]:
# see the shape of the matrix
my_mat.shape

(3, 3)

## Built-in Methods

There are lots of built-in ways to generate arrays.

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
type(np.zeros(3)[0])

numpy.float64

In [15]:
print(type(0.0))
print(type(0.0) == type(0.))
print(np.zeros(3)[0])
print(type(0.0) == type(np.zeros(3)[0]))

<class 'float'>
True
0.0
False


In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((3,3)) + 4

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [20]:
(np.ones((3,3)) + 2) * 200

array([[600., 600., 600.],
       [600., 600., 600.],
       [600., 600., 600.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [21]:
#np.linspace(
#     start,
#     stop,
#     num=50,
#     endpoint=True,
#     retstep=False,
#     dtype=None,
#     axis=0,
# )
# Docstring:
# Return evenly spaced numbers over a specified interval.
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [23]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [25]:
# Uniform Distribution
np.random.rand(2)

array([0.25259427, 0.39833004])

In [26]:
np.random.rand(5,5)

array([[0.5539525 , 0.24275517, 0.99194699, 0.88529863, 0.39272612],
       [0.02445014, 0.04944512, 0.66340705, 0.82066139, 0.21189161],
       [0.74678991, 0.25948393, 0.46622535, 0.50593924, 0.93801603],
       [0.90235777, 0.80622676, 0.78692372, 0.27605026, 0.69321314],
       [0.92202163, 0.59712379, 0.68067643, 0.07929729, 0.04880048]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [18]:
# Normal Distribution
np.random.randn(2)

array([-0.36633217, -1.40298731])

In [27]:
np.random.randn(5,5)

array([[-0.06026612, -0.03317174,  0.42748802,  0.86968009,  0.83142918],
       [-2.13386528, -0.1861901 , -0.1007884 ,  0.70019696,  1.14922584],
       [-1.10973137, -0.11171743,  0.9609189 , -0.11702102,  0.91770489],
       [-0.23369328, -1.40070437,  1.04236096,  2.11048675,  0.4811402 ],
       [-0.68367962,  0.34282601,  1.81132696, -0.60387788, -1.21151517]])

In [32]:
# Choose the mean and standard deviation
# mean==loc=7; sd==scale=27
np.random.normal(loc=7,scale=27,size=((5,5)))

array([[-15.86252198,  32.95880763,  -4.68847502,  11.12042101,
         31.76946781],
       [ 29.38327434,  -6.508973  , -10.23035141, -10.31665439,
         -4.43932521],
       [-17.86661257,  75.11691947, -19.59564202,  37.31506218,
         -4.43836912],
       [-13.23023737,  33.96671052, -21.21096938,  15.45686946,
         14.95135351],
       [ 72.02734213,  43.49879005,  39.21402533,  25.34192503,
        -10.76063559]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [33]:
np.random.randint(1,100)

63

In [36]:
print(len(np.random.randint(1,100,10)))
np.random.randint(1,100,10)

10


array([14, 81, 81, 25, 19, 38, 71, 51, 33, 91])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [37]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
np.random.seed(42)
# np.random.rand(4)

In [39]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [46]:
# create array of [0:24]
arr = np.arange(25)
# Create array of 10 values drawn from [0:50)
ranarr = np.random.randint(0,50,10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr

array([13, 30, 47, 14,  7, 13, 22, 39, 20, 15])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [52]:
ranarr

array([13, 30, 47, 14,  7, 13, 22, 39, 20, 15])

In [53]:
# Return maximum value
ranarr.max()

47

In [59]:
# return location of maximum value
ranarr.argmax()

2

In [56]:
# Return minimum value
ranarr.min()

7

In [57]:
# Return index of minimum value
ranarr.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [60]:
# Vector
arr.shape

(25,)

In [61]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
arr.reshape(1,25).shape

(1, 25)

In [63]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [64]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [65]:
arr.dtype

dtype('int64')

In [66]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Great Job!